### PR TITLE
feat: add more pjlink commands + v2 compatibility

### PR DESCRIPTION
**Pull request by Trickfilm400**
## Changes
- added the possibility to use pjlink v2 commands, the specification was published in 2017 for pjlink 2
- added some commands, see below

## Added Commands
- setVolume
- setVideoMute
- setAudioMute
- setVideoAndAudioMute
- getVideoAndAudioMute
- getInputResolution
- setFreeze
- getFreeze

Would be great if this could me merged soon :)

And feel free to review the changes and provide feedback

### CODE REVIEW

**Comment by Trickfilm400** [comment]
@markschwartzkopf Sorry for bothering you, but could you please take a look at this this week?

**Comment by markschwartzkopf** [comment]
Going to try to merge this this week. Also have some bug fixes I need to get in

**Comment by ensehic** [comment]
Any word on this? Just starting to develop an application that would need to use v2. Would prefer the convenience of using a library over doing it all from scratch 😊

**Comment by Trickfilm400** [comment]
In the meantime I've published my changes currently on npm with my namespace on my github fork

In theory, you could use this

See https://www.npmjs.com/package/@trickfilm400/pjlink-control
(The readme shows the wrong import in case someone wonders)

And
 https://github.com/Trickfilm400/pjlink-control
(Note the different branches)

If you need more commands, just jet me know

**Comment by markschwartzkopf** [comment]
Sorry I've been delayed on this. I am working on it today, and also, hopefully, fixing some minor bugs related to incorrectly closing connections

**Comment by ensehic** [comment]
Thank you both for your effort!

**Pull request merged**
